---
title: "Assignment 3: Data Wrangling in the tidyverse"
subtitle: ECNS 460/560 Fall 2023
date: Due Thursday, September 21
output: html_document
---

***

### Part A: Git to know Git and GitHub

1. *(Required if you're new to Git)* Go through the steps in the slides I showed in class: create a GitHub account, download GitHub Desktop, and connect your account. Then try out the basic workflow: create a new repository on GitHub.com, clone it to your computer using GitHub desktop, add a new file, commit it, push it to the "origin" (remote server), and verify that you can see your new file on the GitHub website. (No need to include anything in your solutions; I'll trust that you've done these steps.)

2. What is your GitHub username? (We need to know to give you credit for the next question.)

3. **Contribute to the joke board.** I'd like you to add a joke to a collaborative list that we can all read. It doesn't have to be good -- the more groan-inducing, the better. (Keep it clean though, please.) You'll do this the same way that you would use to contribute to any collaborative project on GitHub: by creating a **pull request.** A pull request means that *you* are requesting for *me*, the owner of the repo that houses the joke board, to pull and merge *your* changes into my repo. Here's how:

   a. Go to the [joke board repository](https://github.com/msu-econ-data-analytics/joke-board) on the GitHub website. **Fork** it by using the Fork button in the upper right and going to "Create a new fork"; you can keep all the default options. A fork is a parallel version of the joke board repo that exists in your personal account, so you can make whatever changes you want to it without necessarily affecting the original.
   
   a. Now you can **clone** it to your local computer. Open README.md in R or a text editor and add a new joke to the list. Using GitHub Desktop, **commit** your changes and **push** to origin. Your new joke is now synced to your fork of the joke board, but the original repo is not yet modified.
   
   a. Back on the GitHub website, open a **pull request**. Starting from your fork of the joke board, click the "Pull requests" tab and click New Pull Request. It will automatically guess that you want to merge your fork into the original repo. Click "Create pull request" and then again on the next screen.
   
   a. Your job is done at this point. You have to wait for me to approve your pull request before your contribution is reflected in the original repo.
   

### Part B: Wrangling practice

For this section, use data from the `nycflights13` package and tidyverse functions to answer the following questions:

1. What proportion of flights in the entire dataset were canceled? (Hint: you can assume flights without departure or arrival times were canceled.)

2. What month had the highest proportion of canceled flights? What month had the lowest? Interpret any seasonal patterns.

3. Which manufacturers account for the most flights?

4. Is there a relationship between the age of a plane and its delays? (No need for a formal hypothesis test, we're just looking for patterns.)


### Part C: Wrangle some real data

For this section we'll be working with data from the Studying African Farmer-Led Irrigation project in Tanzania and Mozambique. Download the `SAFI_clean` dataset from https://figshare.com/articles/dataset/SAFI_Survey_Results/6262019.

1. Download this dataset and read it into R. Is it in long or wide format? Look at the documentation (i.e. the webpage linked above) to identify the primary key of this dataframe. (A primary key is the variable, or combination of variables, that uniquely identifies each observation in a dataset.) Is the documentation correct?

2. Create a tidy dataframe listing whether each respondent lacked food in each month. Local government officials are wondering: When and where is food aid needed most? Advise them using summary tables.

3. Do respondents who are members of an irrigation association go without food for fewer months than those who aren't? (Again, no need for a statistical test.) Pay attention to the missing values -- what information do/don't you have about what they mean, and how might further information affect the interpretation of your answer?

4. *(ECNS 560 only)* Briefly discuss whether and how this relationship might be causal. What would you advise the government officials to do with this information?

